def countDNA(dna: str) -> str:
  counter = {'A': 0, 'C': 0, 'G': 0, 'T': 0}
  
  for nucleotide in dna:
    if nucleotide in counter:
      counter[nucleotide] += 1
  
  result = " ".join([str(count) for nucleotide, count in counter.items()])
  
  return print(result)

def main() -> None:
  countDNA("TAGAACACTGTTCGTCAACCCGGTACAATAGGATTAGACAGCTTGGGGGCGGCTGGAGACCCCAGCTCGTTCTGCATTGTCGCACGGACCCTACTGGCGAACCGGACCCCAAGCTAGACCAGCGCACACACATAAGTGAATCGATAGTGCCGCGTCCGTACTCAAAGTCAATGGGAGTTCCATGGCCGATTGTTGTGTTTGTCATTAAAACTGCAGCACGTTGACGCGCGCTACCAAGTGAAGTTCTGGGTTTCTATGGATTCTCCGACACCGACCACAAAACGATTTAAGCGAAACGCAAACGAGGATGTAAACTTCGCTCAGGTCGCTTTCTCGTCTGTCCCCACATGAAGTGAACCCCCCACACTAGGAACCGTTCATATGTGATAGTATAGCTCCCTAACTGATTTAGCGCCGTGGCGCGAGCCACAGCGACGTGGTACGCCAACGAGATTGGATACACACTGCGCAGGAGGGAAGCCCCATATTTTTATTCGGCAGAAAAAAGAAGTCTGTCCTACACAACCCCCCGGATTGTGAGGGACCTTCTAGGGGCATGATAGCTAGGGGGTTGATAACCGCCTCATGGGAAATTCGTCGTCTGCCGACCGGTTTTGGAACATATTCGTCGCGACGCAGAACATGCCAGCACCAGGCCCCCCTAACACGGTGCCCTCGCATATTGAACACGTAGGAACCACTTGGATAGATCCCGAACGCTCCCCTTTAAGTGTCGGTCATCGCAGGGTTCCCTATTTTTTGGAACTCGTTTAGAGCAGGAGTTACCGGGTTAGATTGGAGCTAACCGACAGGTATGTATAGATGGACGCAGCGTAGGATCAAAACACGCGGATTAGCTGGGATACCGCAGGTTAAGGCTACAATTGTTAATGGCGCGCTCGGCCGTGAATTCAATAACGATCCCAATATTTACT")

if __name__ == "__main__":
  main()