def reverseComplement(dna: str) -> str:
  mapping: dict = {
    'A' : 'T',
    'C' : 'G',
    'T' : 'A',
    'G' : 'C'
  }
  
  complement: str = "".join([str(mapping[nucleotide]) for nucleotide in dna])[::-1]
  
  return print(complement)

def main():
  reverseComplement("CGTAGTAGTGGTCTTTCTCCCAATTTCGTACCTAAGCTCTGTTTTGGGGTGACTTCAGCGCGCCTAGATCTAATGGTGGTCTGTCTATCGATACGTTGTCGACGTTGTCCAACACGCGCGGTATATCTGAAAAGAGCGCCTGGATGATCCTGCCTGCTCGGCAACTACGATCTCAAGCGAATCCTTCATGGGAAGATAATGGCCTCGCAAAAAGGAGCATTCTCGGACTCAATGGTCCCTTTTGGCCGATCGCAGGAGTCTTGGTACCAGTTCTCGAATCGTGGCCGACTCTGCCTCCCGGGGACTTGGCCGCTATAAAAAGATCTTTATCAGAAGGCTCACTAATGCCCTTTCGCACCTCGCGATTCTCCAAGATAATCTGCTCCTCCGACGCGGGCAGATCTTCAAGCCAGGAATGTGTAGCGGTCGAGCGCTTATCAGCAGGAATCGATGGTAACAGCAGGTTCGAGTATCATTGAACCAACTAACATCGAGAAAAAAACCTCAGTGTCTACTGTCCCAGCGTTTTGGGTACCAGGATTCTGAGTCGAACGTTGAAGCCGTGGGCGTGAGCTAGAATGTACCAGTCTGTTTGACTAAAGTGCATGAGCGAAAAGGACATTAGATACGAGGTTTACCGGTTCGCCCCCCGTCGAACAAGCAATACTGACTTTCCGCCCGCTGGGCTATCATCATATGGTCTCCAAAGAATCTGGTTTCGCACTAACCTCCCGGCCGTCTGCACATACTCTTTCGAGATAAATTCTATTCCGTGTCACCATGAACCGCCTTAGGCGGCTGAGTACGGAACGAGTTGCAGCGTACTTCCATCTGCACGTAGCCAGGCGGTCCGTGGAACACCTGTCGGGTAAAAACATCCGTGTAACGGTGACACTAAAGCGCCGCGGAAATCGGTGTTAAGGATTCCGCACGCTCTGCGGGACCCTTGTTGGCCGATTTTAGTGGTCACGTGGGGCAGCTATTTAG")

if __name__ == "__main__":
  main()